import type { TraceJSON } from '../types'

/**
 * Sample trace data for demo purposes.
 * Simulates a user processing pipeline with nested function calls.
 */
export const sampleTrace: TraceJSON = {
  id: 'sample-trace-001',
  rootSpan: {
    id: 'span-root',
    parentId: null,
    name: 'processOrder',
    input: { orderId: 'ORD-2024-001', userId: 'user-123' },
    output: { status: 'completed', total: 149.97 },
    startTime: 0,
    endTime: 95.5,
    durationMs: 95.5,
    status: 'ok',
    metadata: { module: 'orders' },
    children: [
      {
        id: 'span-1',
        parentId: 'span-root',
        name: 'fetchUser',
        input: 'user-123',
        output: { id: 'user-123', name: 'Alice', email: 'alice@example.com', tier: 'premium' },
        startTime: 0.5,
        endTime: 12.3,
        durationMs: 11.8,
        status: 'ok',
        metadata: { module: 'users', category: 'io' },
        children: [],
      },
      {
        id: 'span-2',
        parentId: 'span-root',
        name: 'validateOrder',
        input: { items: [{ sku: 'LAPTOP-001', qty: 1 }, { sku: 'MOUSE-002', qty: 2 }] },
        output: { valid: true, itemCount: 2 },
        startTime: 12.5,
        endTime: 35.1,
        durationMs: 22.6,
        status: 'ok',
        metadata: { module: 'validation' },
        children: [
          {
            id: 'span-2a',
            parentId: 'span-2',
            name: 'checkInventory',
            input: ['LAPTOP-001', 'MOUSE-002'],
            output: { 'LAPTOP-001': 5, 'MOUSE-002': 23 },
            startTime: 13.0,
            endTime: 25.5,
            durationMs: 12.5,
            status: 'ok',
            metadata: { module: 'inventory', category: 'io' },
            children: [],
          },
          {
            id: 'span-2b',
            parentId: 'span-2',
            name: 'validatePricing',
            input: { items: 2, currency: 'USD' },
            output: { subtotal: 149.97, tax: 12.0, total: 161.97 },
            startTime: 25.8,
            endTime: 34.9,
            durationMs: 9.1,
            status: 'ok',
            metadata: { module: 'pricing' },
            children: [],
          },
        ],
      },
      {
        id: 'span-3',
        parentId: 'span-root',
        name: 'applyDiscount',
        input: { tier: 'premium', subtotal: 149.97 },
        output: { discount: 15.0, reason: 'premium_member' },
        startTime: 35.5,
        endTime: 38.2,
        durationMs: 2.7,
        status: 'ok',
        metadata: { module: 'pricing' },
        children: [],
      },
      {
        id: 'span-4',
        parentId: 'span-root',
        name: 'processPayment',
        input: { amount: 146.97, method: 'credit_card', last4: '4242' },
        output: { transactionId: 'txn-abc123', status: 'approved' },
        startTime: 38.5,
        endTime: 82.0,
        durationMs: 43.5,
        status: 'ok',
        metadata: { module: 'payments', category: 'io' },
        children: [
          {
            id: 'span-4a',
            parentId: 'span-4',
            name: 'chargeCard',
            input: { amount: 146.97, token: 'tok_visa_4242' },
            output: { approved: true, authCode: 'AUTH-789' },
            startTime: 39.0,
            endTime: 75.5,
            durationMs: 36.5,
            status: 'ok',
            metadata: { provider: 'stripe' },
            children: [],
          },
          {
            id: 'span-4b',
            parentId: 'span-4',
            name: 'recordTransaction',
            input: { orderId: 'ORD-2024-001', amount: 146.97 },
            output: { id: 'txn-abc123' },
            startTime: 76.0,
            endTime: 81.5,
            durationMs: 5.5,
            status: 'ok',
            metadata: { module: 'ledger' },
            children: [],
          },
        ],
      },
      {
        id: 'span-5',
        parentId: 'span-root',
        name: 'sendConfirmation',
        input: { email: 'alice@example.com', orderId: 'ORD-2024-001' },
        output: { sent: true, messageId: 'msg-xyz' },
        startTime: 82.5,
        endTime: 95.0,
        durationMs: 12.5,
        status: 'ok',
        metadata: { module: 'notifications', category: 'io' },
        children: [],
      },
    ],
  },
  totalDurationMs: 95.5,
  spanCount: 10,
}

/**
 * Sample trace with a failure path — payment declined.
 */
export const sampleTraceWithError: TraceJSON = {
  id: 'sample-trace-error',
  rootSpan: {
    id: 'err-root',
    parentId: null,
    name: 'processOrder',
    input: { orderId: 'ORD-2024-002', userId: 'user-456' },
    output: undefined,
    startTime: 0,
    endTime: 68.0,
    durationMs: 68.0,
    status: 'error',
    error: 'Payment declined: insufficient funds',
    metadata: { module: 'orders' },
    children: [
      {
        id: 'err-1',
        parentId: 'err-root',
        name: 'fetchUser',
        input: 'user-456',
        output: { id: 'user-456', name: 'Bob', email: 'bob@example.com', tier: 'basic' },
        startTime: 0.5,
        endTime: 8.2,
        durationMs: 7.7,
        status: 'ok',
        metadata: { module: 'users', category: 'io' },
        children: [],
      },
      {
        id: 'err-2',
        parentId: 'err-root',
        name: 'validateOrder',
        input: { items: [{ sku: 'MONITOR-001', qty: 1 }] },
        output: { valid: true, itemCount: 1 },
        startTime: 8.5,
        endTime: 22.0,
        durationMs: 13.5,
        status: 'ok',
        metadata: { module: 'validation' },
        children: [
          {
            id: 'err-2a',
            parentId: 'err-2',
            name: 'checkInventory',
            input: ['MONITOR-001'],
            output: { 'MONITOR-001': 3 },
            startTime: 9.0,
            endTime: 18.0,
            durationMs: 9.0,
            status: 'ok',
            metadata: { module: 'inventory' },
            children: [],
          },
          {
            id: 'err-2b',
            parentId: 'err-2',
            name: 'validatePricing',
            input: { items: 1, currency: 'USD' },
            output: { subtotal: 599.99, tax: 48.0, total: 647.99 },
            startTime: 18.5,
            endTime: 21.8,
            durationMs: 3.3,
            status: 'ok',
            metadata: { module: 'pricing' },
            children: [],
          },
        ],
      },
      {
        id: 'err-3',
        parentId: 'err-root',
        name: 'processPayment',
        input: { amount: 647.99, method: 'credit_card', last4: '1234' },
        output: undefined,
        startTime: 22.5,
        endTime: 65.0,
        durationMs: 42.5,
        status: 'error',
        error: 'Payment declined: insufficient funds',
        metadata: { module: 'payments', category: 'io' },
        children: [
          {
            id: 'err-3a',
            parentId: 'err-3',
            name: 'chargeCard',
            input: { amount: 647.99, token: 'tok_visa_1234' },
            output: undefined,
            startTime: 23.0,
            endTime: 58.0,
            durationMs: 35.0,
            status: 'error',
            error: { code: 'card_declined', message: 'Insufficient funds', decline_code: 'insufficient_funds' },
            metadata: { provider: 'stripe' },
            children: [],
          },
          {
            id: 'err-3b',
            parentId: 'err-3',
            name: 'logFailure',
            input: { orderId: 'ORD-2024-002', reason: 'card_declined' },
            output: { logged: true },
            startTime: 58.5,
            endTime: 64.5,
            durationMs: 6.0,
            status: 'ok',
            metadata: { module: 'audit' },
            children: [],
          },
        ],
      },
    ],
  },
  totalDurationMs: 68.0,
  spanCount: 8,
}
